### ISSUE TITLE
TUM data format

### ISSUE THREAD

**Issue by Chun-Yang1** [engcang/FAST-LIO-SAM-SC-QN#3]
Hello, how can I convert the corrected pose to TUM format and write it to the file

**Comment by engcang** [comment]
@Chun-Yang1 

Hey!
You can refer to this pull request in the FAST-LIO-SAM-QN (without SC) version - https://github.com/engcang/FAST-LIO-SAM-QN/pull/7

I will also apply the commits into this repository in the near future, after all the PRs and enhancements are covered in that repository.
Before then, you can only copy-paste the KITTI or TUM format saving parts.
